### ISSUE TITLE
Mild Typo! 

### ISSUE THREAD

**Issue by hfboyce** [open-data-courses/tree-based-models-in-r#21]
On the home page:

> Contributions and comments on how to improve this course are welcome! Please file an issue or submit a pull request if you find something that could be fixed or improved.

The hyperlink associated with " file an issue " directs to Julia Silge's [supervised ML case studies course](https://github.com/juliasilge/supervised-ML-case-studies-course/issues). 

Just thought you should know! 

- Hayley

**Comment by ledell** [comment]
Thanks @hfboyce!  Fixed: https://github.com/open-data-courses/tree-based-models-in-r/commit/f337aedab18194d4923de288404f5ca03e1c997d
